use chessws2;

create table if not exists users (
    id              int          not null auto_increment,
    name            varchar(64)  not null unique,
    email           varchar(254) not null unique,
    -- passwordHash    varchar(72)  not null,                   -- this is inserted by the web app I am building
    accountType     varchar(64)  not null default("Student"),
    
    primary key(id)
);

create table if not exists tokens (
    token   varchar(124) not null unique,  -- generated by web app
    userid  int          not null,

    primary key(token),
    foreign key(userid) references users(id)
);

create table if not exists classes (
    id      int          not null auto_increment,
    name    varchar(124) not null,
    descr   varchar(500) not null,
    coach   int          not null,

    primary key (id),
    foreign key (coach) references users(id)
);

create table if not exists enrollment (
    userid          int not null,
    classid         int not null,

    foreign key (userid)  references users(id),
    foreign key (classid) references classes(id)
);

create table if not exists assignments (
    id              int          not null auto_increment,
    title           varchar(124) not null,
    descr           varchar(500) not null,
    author          int          not null,

    primary key (id),
    foreign key (author) references users(id)
);

create table if not exists curriculum (
    classid         int not null,
    assignmentid    int not null,

    foreign key (classid)       references classes(id),
    foreign key (assignmentId)  references assignments(id)
);

create table if not exists positions (
    id              int          unique auto_increment,
    assignmentid    int          not null,
    fen             varchar(200) not null, -- see this: https://www.chessprogramming.org/Forsyth-Edwards_Notation
    pgn             varchar(500) not null, -- see this: https://en.wikipedia.org/wiki/Portable_Game_Notation
    points          decimal      not null,

    primary key (id),
    foreign key (assignmentid) references assignments(id)
);

create table if not exists scores (
    positionid int not null,
    userid     int not null,
    points     decimal not null check (points >= 0),

    foreign key (positionid) references positions(id),
    foreign key (userid)     references users(id)
);

SELECT TABLE_NAME, COLUMN_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE CONSTRAINT_NAME = 'PRIMARY'
  AND TABLE_SCHEMA = 'chessws2';
  
SELECT 
    table_name AS 'Table',
    column_name AS 'Column',
    constraint_name AS 'Constraint',
    referenced_table_name AS 'Referenced Table',
    referenced_column_name AS 'Referenced Column'
FROM 
    information_schema.key_column_usage
WHERE 
    referenced_table_name IS NOT NULL
    AND table_schema = 'chessws2';
    
SELECT 
    TC.TABLE_NAME, 
    KCU.COLUMN_NAME, 
    TC.CONSTRAINT_NAME
FROM 
    INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS TC
    JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KCU
    ON TC.CONSTRAINT_NAME = KCU.CONSTRAINT_NAME
WHERE 
    TC.CONSTRAINT_TYPE = 'UNIQUE'
    AND TC.TABLE_SCHEMA = 'chessws2';
    
SELECT 
    TC.TABLE_NAME, 
    CC.CONSTRAINT_NAME, 
    CC.CHECK_CLAUSE
FROM 
    INFORMATION_SCHEMA.CHECK_CONSTRAINTS AS CC
    JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS TC
    ON CC.CONSTRAINT_NAME = TC.CONSTRAINT_NAME
WHERE 
    CC.CONSTRAINT_SCHEMA = 'chessws2';
    
SELECT 
    TABLE_NAME, 
    COLUMN_NAME, 
    COLUMN_DEFAULT
FROM 
    INFORMATION_SCHEMA.COLUMNS
WHERE 
    COLUMN_DEFAULT IS NOT NULL
    AND TABLE_SCHEMA = 'chessws2';